CREATE TABLE CLIENTE (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    NOME VARCHAR(100),
    TELEFONE INT
);

CREATE TABLE PRODUTO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    DESCRICAO VARCHAR(100),
    PRECO_UNIT NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    CLIENTE_ID INT REFERENCES CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    PEDIDO_ID INT REFERENCES PEDIDO (ID),
    PRODUTO_ID INT REFERENCES PRODUTO (ID),
    QTD_PRODUTO INT
);
